### ISSUE TITLE
enablejsapi for youtube

### ISSUE THREAD

**Issue by jiak94** [Justineo/coplay#1]
我看到youtube的api文档说, 要使用api, 要把enablejsapi设置成1. 但是我看了一下代码, 我没有看见你在哪个地方对这个变量设置了. 但是插件确实可以用在youtube的播放器上, 请问是怎么做到的呢?

**Comment by Justineo** [comment]
我调用的是 Youtube 自身网页里的播放器，不是拿他的播放器外嵌到别的地方。他那个应该是已经开启了 JavaScript API 了。
