### ISSUE TITLE
不显示自己的id

### ISSUE THREAD

**Issue by yangweijie** [Justineo/coplay#10]
启用插件不显示自己的id

**Comment by Justineo** [comment]
请双方都在选项中启用默认 PeerJS 服务器

**Comment by Justineo** [comment]
就是扩展的选项里啊，从管理扩展程序的页面里进去。

**Comment by kudoxi** [comment]
![IYZS2@R3G7(AJ7LA}P@)(OQ](https://user-images.githubusercontent.com/30304834/71582291-86596f00-2b44-11ea-8a11-6725f483fa03.png)
不显示PeerID,已经在右上角允许不信任的脚本执行了

**Comment by nanyu328** [comment]
这个问题解决了吗，指导一下~

**Comment by MetLee** [comment]
![image](https://user-images.githubusercontent.com/30506100/75880588-8a618000-5e58-11ea-833e-13a47b9c5073.png)


> 能 具体点 截个图吗

**Comment by MetLee** [comment]
> 这个问题解决了吗，指导一下~

看我截的图
