### ISSUE TITLE
自己搭建peerjs怎么设置?

### ISSUE THREAD

**Issue by cool-delete** [Justineo/coplay#11]
我自己搭建了PeerJS 直接安装在node上了 输入了peerjs --port 9000 --key SeeMovie 启动了 可是把ip和端口还有key输入到选项里面也没有id 默认服务器有id但是不能连接 配置peerjs需要做什么吗 或者有文档给我看嘛

**Comment by cool-delete** [comment]
![20180612103938](https://user-images.githubusercontent.com/13638610/41267178-f6ff474c-6e2c-11e8-8c97-4db9425e1f4d.png)

**Comment by Justineo** [comment]
有报错吗？

**Comment by cool-delete** [comment]
![20180612105509](https://user-images.githubusercontent.com/13638610/41267706-1b21fa8c-6e2f-11e8-8845-c73dc2a6cb7e.png)
解析不出来

**Comment by Justineo** [comment]
你没有写协议头吧……

**Comment by cool-delete** [comment]
怎么写协议头呢

**Comment by Justineo** [comment]
`https://` or `http://`

**Comment by cool-delete** [comment]
![20180612113532](https://user-images.githubusercontent.com/13638610/41268872-b8d92a0c-6e34-11e8-990c-cd13c43b2e95.png)
我这边启动了 peerjs了 就还是没有id 看的腾讯视频

**Comment by Justineo** [comment]
以前需要单独设置允许加载不安全的内容，近期我没测试过了。你还是用默认的服务器吧。或者自己去 Heroku 上部署一个：

[![](https://camo.githubusercontent.com/c0824806f5221ebb7d25e559568582dd39dd1170/68747470733a2f2f7777772e6865726f6b7563646e2e636f6d2f6465706c6f792f627574746f6e2e706e67)](https://www.heroku.com/deploy/?template=https://github.com/peers/peerjs-server)

**Comment by cool-delete** [comment]
明白 可是默认服务器虽然都有id 但是点连接按钮也没反应  我就想直接申请一个公共ip来部署的

**Comment by Justineo** [comment]
双方都能取到 ID 但是连不上？都要设置默认服务器的。

**Comment by cool-delete** [comment]
刚刚开始装的时候的确是连不上的 双方都是默认设置默认服务器没错吧 其中一方翻墙了另一方没有翻墙

**Comment by Justineo** [comment]
毕竟要直连有的时候网络状况导致连不上也的确是存在的，暂时没太好的办法。

**Comment by cool-delete** [comment]
顾大先别关 我看输出console
我手动改成httpca才能访问
![20180612161507](https://user-images.githubusercontent.com/13638610/41278191-d7160c8e-6e5b-11e8-847f-e14d72429ebe.png)
这个需要在服务器怎么设才能支持https的访问呢

**Comment by Justineo** [comment]
你的服务如何支持 HTTPS 和这个项目本身已经没有关系了。

**Comment by cool-delete** [comment]
明白了 那有什么api能控制不去用https访问我这个peer的服务器啊

**Comment by leelaylay** [comment]
默认的代码对于url解析 端口部分有 bug。
基本视频网站都是 HTTPS，因此要求填写的 peerjs 网站是 HTTPS 协议。此时 HTTPS 采用 443 `端口或者缺省情况下，新建的 url 对象 https://github.com/Justineo/coplay/blob/master/extensions/chrome/coplay.js#L662-L664 不会包含任何端口。此时添加undefined到 url 里面会产生 url 对象生成错误。

**Comment by maokwen** [comment]
![image](https://github.com/Justineo/coplay/assets/18361388/f5bf1c00-a8c6-4b11-bb4e-43906a8fabb1)
