### ISSUE TITLE
Update vendor support

### ISSUE THREAD

**Issue by Justineo** [Justineo/coplay#20]
#### Fix support

- [x] Youku
- [x] Tudou
- [x] Tencent Video
- [x] iQiyi
- [x] Sohu
- [x] YouTube
- [x] ACFun
- [x] bilibili
- [x] Vimeo

#### Add support

- [x] MGTV

#### Drop support

- [x] Le

**Comment by KB00100100** [comment]
Cannot work now?

**Comment by Justineo** [comment]
@KB00100100 Work in progress.

**Comment by fansanqiu** [comment]
加油加油！！！！！

**Comment by Justineo** [comment]
Published v0.6.0.
