### ISSUE TITLE
0.60版的firefox插件未打包option文件

### ISSUE THREAD

**Issue by niu541412** [Justineo/coplay#22]
这里的代码和firefox扩展网站的版本相比于chrome版缺失了
options.html和options.js。
导致使用时无法打开设置页面。
firefox还多了个data文件夹。似乎是无用的。
chrome商店似乎未上架新版，不知是不是审核时效的问题

**Comment by Justineo** [comment]
选项是故意去掉的，感觉没有太大的必要了。`data` 文件夹应该是多余的，后面版本删掉。

Chrome 版审核被拒了，我还没搞明白是什么原因……

**Comment by drcege** [comment]
你好，能在 release 里上传下 crx 吗。。。chrome 商店实在不方便，我从其他网站下载下来也是 0.5.0

**Comment by niu541412** [comment]
我自己 尝试了一下上传新版到商店并不公开。都通过了。
chrome商店似乎是要求使用新版的开发者中心，并且要把permission的几项使用原因写清楚。
firefox版的manifest.json里applications这个key似乎从firefox57+就不再需要，[Firefox MDN](https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings)，并且和option文件冲突。删除这个key后就可以和chrome版打包文件完全一致。😆

**Comment by Justineo** [comment]
Chrome Webstore 给我的理由是：

> Your item did not comply with the following section of our policy:
> Do not use irrelevant, misleading, or **excessive keywords** in app descriptions, titles, or metadata.

而我的描述内容是：

> Coplay connects two remote browsers with WebRTC (using PeerJS) and enables users from either side control video play on both sides.
> Coplay now works on Youku, Sohu TV, Tencent Video, Tudou, iQiyi, YouTube, ACFun, bilibili, Vimeo and MGTV.

我回复审核邮件询问理由以后，得到了一个回复，把前一个回复给我复读了一遍……
