### ISSUE TITLE
优酷无法使用

### ISSUE THREAD

**Issue by MetLee** [Justineo/coplay#24]
大佬好，感谢大佬的插件！我在b站尝试了下可以正常使用，但是优酷那个小爱心加载不出，请问下会不会是优酷的接口有所改动？

**Comment by Justineo** [comment]
Chrome 版本更新被拒了，请先尝试使用 Firefox 版本。

**Comment by MetLee** [comment]
> Chrome 版本更新被拒了，请先尝试使用 Firefox 版本。

好的明白了，谢谢大佬
