### ISSUE TITLE
A step-by-step setup guide?

### ISSUE THREAD

**Issue by Pyroglyph** [Justineo/coplay#3]
Not all of us are familiar with deploying apps and PeerJS and such. A step-by-step guide would be very much appreciated by many people :)

**Comment by Justineo** [comment]
Hi, do you mean you want to deploy a PeerJS server yourself?

**Comment by Pyroglyph** [comment]
Yes, unless there is another way to do it?

**Comment by Justineo** [comment]
You can follow the instructions [here](https://github.com/peers/peerjs-server) to set up your own PeerJS server.

Or you can just make your browser to allow insecure requests from HTTPS sites like YouTube. The workaround is mentioned in the [readme](https://github.com/Justineo/coplay#faq) file.

**Comment by Justineo** [comment]
@599316527 has already set up a PeerJS server on his personal site. Maybe you can use that in your extension options right now. But there's no guarantee that this service will be always available.

I thinks we can make a list of these private servers for users who cannot build their own server.

| Server | Key | Provider |
| --- | --- | --- |
| `https://peer.adeline.cc:8520/` | `OECd4rcvUqk487Yt6X` | @599316527 (Kyle He) |
