### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by FENG-MASTER** [Justineo/coplay#6]
我测试的时候,自己本地和本地的浏览器(谷歌的那款)是可以完全同步的,就是可以连接的,但是如果是异地就不可以了,我用的是优酷的.. 提供下地址你看看..http://v.youku.com/v_show/id_XMTcyNTY0NDQyNA==.html?tpa=dW5pb25faWQ9MTAyMjEzXzEwMDAwOF8wMV8wMQ&from=360sousuo&refer=360sousuo&qq-pf-to=pcqq.c2c

具体情况是无法连接.不知道原因.但连接自己本地的同一个电脑上的浏览器是可以的,希望快点得到解决

补充说明下,地域一个在成都,一个广州,不知道有影响不

**Comment by FENG-MASTER** [comment]
更新下说明,不是连接不上,是只能单方面连接,比如A和B,假设A主动连接B,那么B那边的显示是连接成功,但A那边还是显示不成功,不知道原因

**Comment by Justineo** [comment]
Coplay 依赖了 PeerJS 提供的服务来进行连接，同时也和使用者的网络环境相关，有时候的确会连接不上，很难排查原因。

**Comment by FENG-MASTER** [comment]
那是否可以自己搭服务器，能的话怎么搭？我看设置里可以设置一个服务地址？很喜欢你做的这个小插件，能用的话真的是帮了大忙了，有什么方法可以解决上面的情况吗？我能做到的

**Comment by Justineo** [comment]
PeerJS 的 server 可以自己部署，可以参考一下 #3 里说的。

**Comment by FENG-MASTER** [comment]
用了3的提供的地址,还是不行,只能稍微近距离的网络才可以,我试了手机4G开无线和本地电信的另一台电脑用coplay可以连接...但跨省就不可以,

**Comment by 599316527** [comment]
@FENG-MASTER #3 中的服务器在加州，也许是墙的关系，国内有些地方、有些运营商没法访问 🙃

**Comment by Justineo** [comment]
即使两边都连上了 PeerJS server 有时候连接还是会失败，这个我也没法调试……
